sudo: false
notifications:
  email: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - stable
before_script:
  - npm prune
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - npm run semantic-release
